### ISSUE TITLE
Xcode Swift Package Manager only adds version 1.0.2

### ISSUE THREAD

**Issue by hartti** [indieSoftware/NavigationStack#3]
I do not seem to find a way to add the 1.1.0 version with Xcode SPM. I only manage up to 1.0.2.
Are the SPM required files up-to-date or is this just a user error?

Steps to reproduce:
1) create a new SwiftUI app project
2) try to add the NavigationStack to this project with Swift Package Manager. The latest version I am able to import is 1.0.2. It does not matter what selection or version numbers I choose (Up to next major version, Up to next minor version, Exact version with 1.1.0, or Range)

**Comment by indieSoftware** [comment]
Thanks for pointing that out, seems I used a wrong tag version number format for SPM ("1.1" instead of "1.1.0"). Should be fixed now.
