### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by saket** [indieSoftware/NavigationStack#4]
Hey @indieSoftware thanks for maintaining this library! I was wondering if support for macOS be added to NavigationStack? [I tried it out in a fork](https://github.com/saket/NavigationStack/commit/4b3510a455dad5b78cd19bed135eaa418510ae75#diff-af2b391b8977dc5c9a84dc0bdb7db7c53e56d66ad95188882d9beb9fbc2cef88) and it seems to work. I couldn't find any code that's specific to iOS.

**Comment by indieSoftware** [comment]
Hi @saket, thanks for your feedback. I have added the CocoaPods and SPM support for macOS and updated the demo app to also run as a Mac build. This should hopefully make the lib available to your mac project. Can you please verify that this works with v1.1.1 for you? Thanks!

**Comment by saket** [comment]
It works, thank you!
